# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JnRYFYkAnaJv6JvD6GuEGVSEalczP176
"""

# from google.colab import drive
# drive.mount('/content/drive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/My Drive/Colab Notebooks/IREProject/Multimodal Hashtag Generation/CVPR json'

# !ls -1 *.json

# !pip install instaloader

import json
import instaloader
import argparse
from tqdm import tqdm as tqdm

class InstaloaderException(Exception):
  '''Copied from source code to hadnle error'''
  pass

class QueryReturnedNotFoundException(InstaloaderException):
  '''Copied from source code to hadnle error'''
  pass

data = None
with open('insta-hashtag-train.json') as f:
  data = json.load(f)

parser = argparse.ArgumentParser(description='Get comments for each post of each users in insta-hashtag-dataset')
parser.add_argument('startIndx', type=int, help='start index for users')
parser.add_argument('endIndx', type=int, help='closing index for users')
args = parser.parse_args()
# print(args.startIndx)
# print(args.endIndx)

L = instaloader.Instaloader()
instaComments = {}

allUsers = list(data.keys())
# with tqdm(total=len(allUsers[args.startIndx:args.endIndx + 1])) as pbar:
for idx in tqdm(range(args.startIndx, args.endIndx + 1)):
  # pbar.update(1)
  post,profile = None, None
  try:
    profile = instaloader.Profile.from_id(L.context,allUsers[idx])
  except:
    continue
  for mediaID in list(data[allUsers[idx]].keys()):
    try:
      post = instaloader.Post.from_mediaid(L.context, int(mediaID.split('_')[0]))
      L.download_post(post,f'{allUsers[idx]}')
    except:
      continue
